# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: astral-sh.ty
PackageVersion: 0.0.7
PackageLocale: en-US
Publisher: Astral Software Inc.
PublisherUrl: https://astral.sh/
PublisherSupportUrl: https://github.com/astral-sh/ty/issues
Author: Astral Software Inc.
PackageName: ty
PackageUrl: https://github.com/astral-sh/ty
License: MIT
LicenseUrl: https://github.com/astral-sh/ty/blob/HEAD/LICENSE
Copyright: Copyright (c) 2025 Astral Software Inc.
CopyrightUrl: https://github.com/astral-sh/ty/blob/HEAD/LICENSE
ShortDescription: An extremely fast Python type checker and language server, written in Rust.
Moniker: ty
Tags:
- python
ReleaseNotes: |-
  Bug fixes
  - Fix classification of modules in import x as y for semantic syntax highlighting (#22175)
  - Fix module resolution on network drives (#22173)
  - Render the entire diagnostic message in all output formats (#22164)
  Other changes
  - Add a dedicated diagnostic for TypedDict deletions (#22123)
  - Check __delitem__ instead of __getitem__ for del x[k] (#22121)
  - Fix @staticmethod combined with other decorators incorrectly binding self (#22128)
  - Fix implementation of Top[Callable[..., object]] (#22145)
  - Improve diagnostic when callable is used in a type expression instead of collections.abc.Callable or typing.Callable (#22180)
  - Improve diagnostic when a user tries to access a function attribute on a Callable type (#22182)
  - Include the specialization of a generic TypedDict as part of its display (#22174)
  - Support tuple narrowing based on member checks (#22167)
  - Synthesize __delitem__ for TypedDict to allow deleting non-required keys (#22122)
  Contributors
  - @MichaReiser
  - @ntBre
  - @AlexWaygood
  - @charliermarsh
ReleaseNotesUrl: https://github.com/astral-sh/ty/releases/tag/0.0.7
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://docs.astral.sh/ty/
ManifestType: defaultLocale
ManifestVersion: 1.12.0
